var zoznamTimov = [     //do tabulky
    'Fero',
    'Adam',
    'Jozef',
    'Magi',
    'Magi',
    'Magi'
];
var pocetPiesni = 4;
var pocetVidei = 4;
var zoznamOtazok = [     //do Party
    'Ako sa volá ujo na obrázku?',
    'Naco je ujovi mikrofon?',
    'Preco to spravili?',
    'Na com sa smeje?',
    '555',
    '6666',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1',
    // '1'
];
